[project]
name = "open-med-calc"
version = "0.1.0"
description = "Open source medical calculator API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.1",
    "numpy>=1.26.2",
    "pydantic>=2.4.2",
    "uvicorn[standard]>=0.24.0",
]
